kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres
  labels:
    app: kutuapp
    component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kutuapp
      component: postgres
  template:
    metadata:
      labels:
        app: kutuapp
        component: postgres
    spec:
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: kutu-data
        - name: postgres-config
          configMap:
            name: postgres-config
      containers:
        - resources:
            limits:
              memory: 1Gi
            requests:
              memory: 64Mi
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  psql -h 127.0.0.1 -U $POSTGRESQL_USER -q -d kutudb -c 'SELECT
                  1'
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: postgres
          env:
            - name: POSTGRESQL_DATABASE
              value: kutuapp
            - name: POSTGRESQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kutu-postgres-secret
                  key: adminpassword            
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: kutu-postgres-secret
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kutu-postgres-secret
                  key: password
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: kutu-data
              mountPath: /var/lib/pgsql/data
            - name: postgres-config
              readonly: true
              mountPath: /docker-entrypoint-initdb.d/  
          terminationMessagePolicy: File
          image: postgres:12.1-alpine
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
