kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: master-dbeee78
  ports:
    http:
      containerPort: 5757
  network:
    frontend:
      servicePort: 5757
      ingress:
        host: competition-test.sharevic.net
  ingress:
    zone: ch
  service:
    type: ClusterIP        
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  # env:
  # - name: SPRING_PROFILES_ACTIVE
  #   value: dev
  persistence:
    name: kutu-data
    # storageClass: trident-nfs
    enabled: false
    # accessModes: ReadWriteMany
    # size: 1Gi

  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: appdataroot
    name: kutuapp-data
  - mountPath: /home/kutuapp/data
    subPath: data
    name: kutuapp-data
  - mountPath: /home/kutuapp/db
    subPath: db
    name: kutuapp-data
