kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: master-dbeee78
  ports:
    http:
      containerPort: 5757
  network:
    frontend:
      servicePort: 5757
      ingress:
        host: competition-test.sharevic.net
  ingress:
    zone: ch
  service:
    type: ClusterIP        
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  # env:
  # - name: SPRING_PROFILES_ACTIVE
  #   value: dev
  persistence:
    name: kutu-data
    enabled: false
  volumes:
  - name: kutu-data
    persistentVolumeClaim:
      claimName: kutu-data
  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: appdataroot
    name: kutu-data
  - mountPath: /home/kutuapp/data
    subPath: data
    name: kutu-data
  - mountPath: /home/kutuapp/db
    subPath: db
    name: kutu-data
