kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: master-263041c
  ports:
    http:
      containerPort: 5757
# find a way, how to activate more than one route ...      
#  ingress:
#    enabled: true
#    host: kutuapp-test.apps.okd.baloise.dev
  ingress:
    enabled: true
    host: competition.sharevic.net
    wildcardPolicy: Subdomain

  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  # env:
  # - name: SPRING_PROFILES_ACTIVE
  #   value: dev
  volumes:
  - name: kutu-data
    emptyDir: {}

  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: appdataroot
    name: kutu-data
  - mountPath: /home/kutuapp/data
    subPath: data
    name: kutu-data
  - mountPath: /home/kutuapp/db
    subPath: db
    name: kutu-data