kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: feature.wettkampf-subscription-c946d3f
  network:
    http:
      servicePort: 5757
      # ingress:
      #  host: competition.sharevic.net
  service:
    type: ClusterIP        
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  env:
    - name: X_DB_CONFIG_NAME
      value: kutudb_pg
    - name: X_POSTGRES_HOST
      value: postgres
    - name: X_POSTGRES_USER
      value: kutuapp
    - name: X_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kutu-postgres-secret
          key: password

  persistence:
    enabled: true
    name: kutuapp-data
    storageClass: cephfs
    accessModes: ReadWriteMany
    size: 1Gi
    annotations:
      pv.kubernetes.io/bound-by-controller: 'yes'
      volume.beta.kubernetes.io/storage-provisioner: rook-ceph.rbd.csi.ceph.com
  # volumes:
  # - name: kutuapp-data
  #    persistentVolumeClaim:
  #     claimName: kutu-data
  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: appdataroot
    name: kutuapp-data
  - mountPath: /home/kutuapp/data
    subPath: data
    name: kutuapp-data
  - mountPath: /home/kutuapp/db
    subPath: db
    name: kutuapp-data
