kutudb:
  replicaCount: 1
  image:
    repository: postgres
    tag: 9.4
  ports:
    http:
      containerPort: 5432
  env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
  volumeMounts:
    - mountPath: /var/lib/postgresql/data
      subPath: appdataroot
      name: kutu-data    
  volumes:
    - name: kutu-data
      persistentVolumeClaim:
        claimName: kutu-data
        
kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: master-dbeee78
  ports:
    http:
      containerPort: 5757
  ingress:
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  # env:
  # - name: SPRING_PROFILES_ACTIVE
  #   value: dev

  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: appdataroot
    name: kutu-data
  - mountPath: /home/kutuapp/data
    subPath: data
    name: kutu-data
  - mountPath: /home/kutuapp/db
    subPath: db
    name: kutu-data
    
  volumes:
    - name: kutu-data
      persistentVolumeClaim:
        claimName: kutu-data