kutuapp:
  replicaCount: 1
  image:
    repository: luechtdiode/kutuapp
    tag: master-dbeee78
  ports:
    http:
      containerPort: 5757
  network:
    frontend:
      servicePort: 5757
      ingress:  {}
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  # env:
  # - name: SPRING_PROFILES_ACTIVE
  #   value: dev
  persistence:
    name: kutuapp-data
    storageClass: custom-storage-class
    enabled: true
    accessModes: ReadWriteMany
    size: 1Gi

  volumeMounts:
  - mountPath: /home/kutuapp
    subPath: appdataroot
    name: kutuapp-data
  - mountPath: /home/kutuapp/data
    subPath: data
    name: kutuapp-data
  - mountPath: /home/kutuapp/db
    subPath: db
    name: kutuapp-data
